# -*- coding: utf8 -*-
# ============LICENSE_START====================================================
# org.onap.vvp/validation-scripts
# ===================================================================
# Copyright © 2019 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the "License");
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the "License");
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
#
namespace: org.onap.vvp
owner: ONAP
ui:
  app-name: VNF Validation Tool
categories:
  - name: Environment File Compliance. (Required to Onboard)
    category: environment_file
    description:
      Checks certain parameters are excluded from the .env file, per HOT Requirements.
      Required for ASDC onboarding, not needed for manual Openstack testing.
  - name: OpenStack Heat Testing (Beta)
    category: openstack
    description:
      Uses the latest OpenStack Heat community version available to validate that
      a heat template is valid OpenStack Heat. This testing is equivalent to using
      heat template-validate from the command line.
additional-cnf-tests:
  - name: Srtict Helm lint test
    test: strict_helm_lint
    description:
      Runs 'helm lint --strict' on Helm charts. Warnings are also considered as errors.
  - name: LICENSE present in each Helm chart
    test: license_present_in_helm
    description:
      Tests if LICENSE file is present in Helm charts or not
  - name: README.md present in Helm chart
    test: readme_present_in_helm
    description:
      Tests if README.md file is present in Helm charts or not
  - name: appVersion present in Chart.yaml
    test: appVersion_present
    description:
      Tests if appVersion is present in Chart.yaml in Helm charts
  - name: appVersion value wrapped in quotes
    test: appVersion_in_quotes
    description:
      Tests if appVersion value is wrapped in quotes in Chart.yaml in Helm chart
  - name: templates/NOTES.txt present in Helm chart
    test: notes_present_in_templates
    description:
      Tests if NOTES.txt is present in templates/ in Helm chart, if templates directory exists
  - name: Verify Helm integrity
    test: helm_verify_integrity
    description:
      Run 'helm verify' test on Helm charts

    
settings:
  polling-freqency: 1000
